extends SceneTree

const ModelGalleryUtil := preload("res://scripts/gallery/model_gallery.gd")


func _init() -> void:
	var gallery := ModelGalleryUtil.new()
	root.add_child(gallery)
	await process_frame

	assert(gallery.candidate_count() == 3)
	assert(gallery.category_count() == 25)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE))
	assert(not gallery.visible)
	gallery.set_active(true)
	assert(gallery.visible)
	assert(gallery.gallery_layer.visible)
	var initial_basis := gallery.candidate_roots[0].basis
	gallery.update_gallery(0.5)
	assert(not gallery.candidate_roots[0].basis.is_equal_approx(initial_basis))
	assert(absf(gallery.candidate_roots[0].rotation.x) > 0.01)
	gallery.change_category(1)
	assert(gallery.category_index == 1)
	assert(gallery.candidate_count() == 3)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE))
	gallery.change_category(1)
	assert(gallery.category_index == 2)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE))
	gallery.change_category(1)
	assert(gallery.category_index == 3)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 2.7))
	gallery.change_category(1)
	assert(gallery.category_index == 4)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 0.82))
	assert(gallery.candidate_roots[0].find_child("zakoM0-stepped-wall", true, false) != null)
	assert(gallery.candidate_roots[1].find_child("zakoM0-inner-citadel", true, false) != null)
	assert(gallery.candidate_roots[2].find_child("zakoM0-lattice-keep", true, false) != null)
	var crystal_plates := gallery.candidate_roots[2].find_children("zakoM0-crystal-plate-*", "Node3D", true, false)
	assert(crystal_plates.size() == 3)
	for crystal_plate in crystal_plates:
		assert(is_zero_approx((crystal_plate as Node3D).rotation.y))
	gallery.change_category(1)
	assert(gallery.category_index == 5)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 2.2))
	gallery.change_category(1)
	assert(gallery.category_index == 6)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE))
	gallery.change_category(1)
	assert(gallery.category_index == 7)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 2.8))
	gallery.change_category(1)
	assert(gallery.category_index == 8)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE))
	gallery.change_category(1)
	assert(gallery.category_index == 9)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 2.8))
	gallery.change_category(1)
	assert(gallery.category_index == 10)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE))
	gallery.change_category(1)
	assert(gallery.category_index == 11)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 0.78))
	gallery.change_category(1)
	assert(gallery.category_index == 12)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 1.7))
	gallery.change_category(1)
	assert(gallery.category_index == 13)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE))
	gallery.change_category(1)
	assert(gallery.category_index == 14)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 2.0))
	gallery.change_category(1)
	assert(gallery.category_index == 15)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 1.45))
	gallery.change_category(1)
	assert(gallery.category_index == 16)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 2.6))
	assert(gallery.candidate_roots[0].name == "BossB1PaleRect")
	gallery.change_category(1)
	assert(gallery.category_index == 17)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 0.82))
	assert(is_equal_approx(ModelGalleryUtil.BOSS_CAGED_CORE_OUTLINE_WIDTH, 0.040))
	assert(is_equal_approx(ModelGalleryUtil.BOSS_CAGED_PRIMARY_RING_WIDTH, 0.032))
	assert(is_equal_approx(ModelGalleryUtil.BOSS_CAGED_SECONDARY_RING_WIDTH, 0.065))
	assert(is_equal_approx(ModelGalleryUtil.BOSS_T_SLOW_GUN_EDGE_WIDTH, 0.015))
	for candidate in gallery.candidate_roots:
		assert(candidate.find_child("boss-core-visual", true, false) != null)
		assert(candidate.find_child("boss-core-gun-orbit", true, false) != null)
	var gapped_outer := gallery.candidate_roots[0].find_child("boss-core-ring-cw-outer", true, false) as Node3D
	var complete_outer := gallery.candidate_roots[1].find_child("boss-core-ring-cw-outer-complete", true, false) as Node3D
	assert(gapped_outer != null)
	assert(complete_outer != null)
	assert(gapped_outer.get_child_count() < complete_outer.get_child_count())
	var saturn_outer := gallery.candidate_roots[2].find_child("boss-core-ring-cw-outer-saturn", true, false) as Node3D
	assert(saturn_outer != null)
	assert(saturn_outer.get_child_count() == 1)
	assert(saturn_outer.get_child(0) is MeshInstance3D)
	var clockwise_ring := gallery.candidate_roots[0].find_child("boss-core-ring-cw*", true, false) as Node3D
	var counterclockwise_ring := gallery.candidate_roots[0].find_child("boss-core-ring-ccw*", true, false) as Node3D
	var gun_orbit := gallery.candidate_roots[0].find_child("boss-core-gun-orbit", true, false) as Node3D
	var clockwise_basis := clockwise_ring.basis
	var counterclockwise_basis := counterclockwise_ring.basis
	var gun_orbit_basis := gun_orbit.basis
	gallery.update_gallery(0.5)
	assert(not clockwise_ring.basis.is_equal_approx(clockwise_basis))
	assert(not counterclockwise_ring.basis.is_equal_approx(counterclockwise_basis))
	assert(not gun_orbit.basis.is_equal_approx(gun_orbit_basis))
	gallery.change_category(1)
	assert(gallery.category_index == 18)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 0.72))
	assert(gallery.candidate_roots[0].find_child("boss-t1-core-anchor", true, false) != null)
	gallery.change_category(1)
	assert(gallery.category_index == 19)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 3.1))
	assert(gallery.candidate_roots[0].name == "MyshotWireDiamond")
	assert(gallery.candidate_roots[1].name == "MyshotCoreLance")
	assert(gallery.candidate_roots[2].name == "MyshotOpenSpark")
	gallery.change_category(1)
	assert(gallery.category_index == 20)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 2.4))
	assert(gallery.candidate_roots[0].name == "MousetargetCornerSweep")
	var sweep := gallery.candidate_roots[0].find_child("mousetarget-visibility-sweep", true, false) as Node3D
	assert(sweep != null)
	var sweep_basis := sweep.basis
	gallery.update_gallery(0.25)
	assert(not sweep.basis.is_equal_approx(sweep_basis))
	gallery.change_category(1)
	assert(gallery.category_index == 21)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 2.4))
	assert(gallery.candidate_roots[0].name == "GumLayeredOrb")
	assert(gallery.candidate_roots[1].name == "GumShellRings")
	assert(gallery.candidate_roots[2].name == "GumLowEnergyCore")
	assert(not gallery.candidate_roots[0].find_children("*", "MeshInstance3D", true, false).is_empty())
	gallery.change_category(1)
	assert(gallery.category_index == 22)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 1.6))
	assert(gallery.candidate_roots[0].name == "MycharCannonWheels")
	assert(gallery.candidate_roots[1].name == "MycharBoosterShip")
	assert(gallery.candidate_roots[2].name == "MycharArmoredPods")
	assert(not gallery.candidate_roots[0].find_children("*", "MeshInstance3D", true, false).is_empty())
	gallery.change_category(1)
	assert(gallery.category_index == 23)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 0.85))
	assert(gallery.candidate_roots[0].name == "ASinuousRibbon")
	assert(gallery.candidate_roots[1].name == "BNodeTether")
	assert(gallery.candidate_roots[2].name == "CHighArch")
	assert(not gallery.candidate_roots[0].find_children("*", "MeshInstance3D", true, false).is_empty())
	gallery.change_category(1)
	assert(gallery.category_index == 24)
	assert(gallery.candidate_count() == 1)
	assert(gallery.candidate_roots[0].scale.is_equal_approx(Vector3.ONE * 4.0))
	assert(gallery.candidate_roots[0].has_meta("manual_gallery_rotation"))
	assert(gallery.wants_clean_background())

	gallery.queue_free()
	await process_frame
	await process_frame
	print("model gallery verification passed")
	quit()
