extends SceneTree

const BulletManagerUtil := preload("res://scripts/game/bullet_manager.gd")
const EnemyUtil := preload("res://scripts/game/enemy.gd")


func _init() -> void:
	assert(is_equal_approx(BulletManagerUtil.SHOT_SPEED, 24.0))
	assert(is_equal_approx(BulletManagerUtil.BULLET0_SPEED, 1.8))
	assert(is_equal_approx(BulletManagerUtil.BULLET1_SPEED, 7.5))
	assert(is_equal_approx(BulletManagerUtil.BULLET2_SPEED, 4.5))
	assert(is_equal_approx(BulletManagerUtil.BOSS_B1_SPEED, 6.0))
	assert(is_equal_approx(BulletManagerUtil.BOSS_B2_SPEED, 4.5))
	assert(is_equal_approx(BulletManagerUtil.HOSTILE_DIRECTION_LINE_LENGTH, 0.90))
	assert(is_inf(BulletManagerUtil.DEFAULT_HOSTILE_BULLET_LIFETIME))
	assert(is_equal_approx(EnemyUtil.ZAKO0_SPEED, 5.25))
	assert(is_equal_approx(EnemyUtil.ZAKO1_SPEED, 1.5))
	assert(is_equal_approx(EnemyUtil.ZAKO2_SPEED, 3.0))
	assert(is_equal_approx(EnemyUtil.ZAKO2_HOMING_SPEED, 0.3))
	assert(is_equal_approx(EnemyUtil.ZAKO2_VISUAL_SPIN_SPEED, deg_to_rad(600.0)))
	assert(is_equal_approx(EnemyUtil.ZAKO3P_SPEED, 3.0))
	assert(is_equal_approx(EnemyUtil.ZAKO4_SPEED, 1.5))
	assert(is_equal_approx(EnemyUtil.ZAKO5_SPEED, 5.25))
	assert(is_equal_approx(EnemyUtil.ZAKO6_SPEED, 6.0))
	assert(is_equal_approx(EnemyUtil.ZAKO7_SPEED, 3.0))
	assert(is_equal_approx(EnemyUtil.ZAKO7P_SPEED, 3.0))
	assert(is_equal_approx(EnemyUtil.ZAKOM1_SPEED, 3.0))
	var zako2_node := Node3D.new()
	var zako2 := EnemyUtil.create_zako("zako2", zako2_node, Vector2.ZERO, 0.0, Color.WHITE, -1)
	assert(is_equal_approx(absf(zako2.spin), EnemyUtil.ZAKO2_VISUAL_SPIN_SPEED))
	zako2_node.free()
	var zako3_node := Node3D.new()
	var zako3 := EnemyUtil.create_zako("zako3", zako3_node, Vector2.ZERO, 0.0, Color.WHITE, -1)
	assert(is_equal_approx(zako3.tumble_axis.length(), 1.0))
	assert(absf(zako3.tumble_speed) >= EnemyUtil.ZAKO3_TUMBLE_SPEED_MIN)
	assert(absf(zako3.tumble_speed) <= EnemyUtil.ZAKO3_TUMBLE_SPEED_MAX)
	zako3_node.free()
	quit()
